import type { Product } from "./types";

const u = (q: string) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=900&q=80`;

export const SUGGESTED_CATALOG: Product[] = [
  {
    id: "sug-cleanse-1",
    brand: "Lumea",
    name: "Velvet Cream Cleanser",
    category: "cleanser",
    tags: ["hydrating", "barrier-repair", "fragrance-free"],
    notes:
      "Cushioning gel-cream with oat and ceramides. Pulls off makeup without stripping.",
    price: 28,
    priceCurrency: "USD",
    image: u("photo-1556228720-195a672e8a03"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-cleanse-2",
    brand: "Solene",
    name: "Quartz Foam Wash",
    category: "cleanser",
    tags: ["balancing", "niacinamide"],
    notes: "Lightweight foam for warm, sticky days. Won't suds the skin dry.",
    price: 24,
    priceCurrency: "USD",
    image: u("photo-1571781926291-c477ebfd024b"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-toner-1",
    brand: "Maren",
    name: "Dewdrop Essence",
    category: "toner",
    tags: ["hydrating", "hyaluronic", "calming"],
    notes: "A watery essence that disappears into thirsty skin.",
    price: 32,
    priceCurrency: "USD",
    image: u("photo-1620916566398-39f1143ab7be"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-serum-vc",
    brand: "Solene",
    name: "Sun Drops Vitamin C 12%",
    category: "serum",
    tags: ["brightening", "antioxidant", "vitamin-c"],
    notes: "Stable C with ferulic. Wakes a tired complexion in 10 minutes.",
    price: 58,
    priceCurrency: "USD",
    image: u("photo-1611080626919-7cf5a9dbab12"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-serum-ha",
    brand: "Maren",
    name: "Glasswater Hydrating Serum",
    category: "serum",
    tags: ["hydrating", "hyaluronic", "ceramides"],
    notes: "Layered hyaluronic weights plus 3 ceramides. Drink for the face.",
    price: 46,
    priceCurrency: "USD",
    image: u("photo-1631730486784-5c52cf6e2f2b"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-serum-niac",
    brand: "Lumea",
    name: "Quiet Niacinamide 6%",
    category: "serum",
    tags: ["balancing", "niacinamide", "calming"],
    notes: "Calms redness and softens texture without flaking.",
    price: 36,
    priceCurrency: "USD",
    image: u("photo-1608248543803-ba4f8c70ae0b"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-serum-azel",
    brand: "Tara",
    name: "Stillness Azelaic 10%",
    category: "serum",
    tags: ["calming", "azelaic", "anti-inflammatory"],
    notes: "For days the mirror feels louder than usual.",
    price: 42,
    priceCurrency: "USD",
    image: u("photo-1612817288484-6f916006741a"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-moist-1",
    brand: "Lumea",
    name: "Cashmere Barrier Cream",
    category: "moisturizer",
    tags: ["hydrating", "barrier-repair", "ceramides", "fragrance-free"],
    notes: "Slow-absorbing, occlusive enough for cold cabin air.",
    price: 52,
    priceCurrency: "USD",
    image: u("photo-1617897903246-719242758050"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-moist-2",
    brand: "Solene",
    name: "Air Gel Moisturizer",
    category: "moisturizer",
    tags: ["hydrating", "balancing"],
    notes: "Almost weightless. The match for a humid day.",
    price: 38,
    priceCurrency: "USD",
    image: u("photo-1556228453-efd6c1ff04f6"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-eye-1",
    brand: "Maren",
    name: "Dawn Eye Concentrate",
    category: "eye",
    tags: ["depuffing", "peptides", "brightening"],
    notes: "Cooling caffeine and peptides to deflate undereye luggage.",
    price: 44,
    priceCurrency: "USD",
    image: u("photo-1599305445671-ac291c95aaa9"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-spf-1",
    brand: "Helia",
    name: "Daylight SPF 50",
    category: "spf",
    tags: ["spf", "antioxidant"],
    notes: "Invisible mineral with green tea. No white cast on warm tones.",
    price: 36,
    priceCurrency: "USD",
    image: u("photo-1556228841-a3c527ebefe5"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-mask-1",
    brand: "Tara",
    name: "Overnight Honey Mask",
    category: "mask",
    tags: ["hydrating", "barrier-repair"],
    notes: "Sleep mask that drinks itself in. Wake up plumped.",
    price: 48,
    priceCurrency: "USD",
    image: u("photo-1620916297893-9b5a08b14a91"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-exfo-1",
    brand: "Solene",
    name: "Sunday PHA Polish",
    category: "exfoliant",
    tags: ["exfoliating", "brightening"],
    notes: "Gentler than glycolic. Use 1–2 evenings a week.",
    price: 34,
    priceCurrency: "USD",
    image: u("photo-1608248511-0f6ddb2cca6b"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-oil-1",
    brand: "Lumea",
    name: "Neroli Glow Oil",
    category: "oil",
    tags: ["hydrating", "antioxidant"],
    notes: "Three drops over moisturizer for that lit-from-within finish.",
    price: 64,
    priceCurrency: "USD",
    image: u("photo-1597305877032-0668b3c6413a"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-mist-1",
    brand: "Maren",
    name: "Petal Mist",
    category: "mist",
    tags: ["hydrating", "calming"],
    notes: "Carry-on size. A 4 PM reset for travel skin.",
    price: 22,
    priceCurrency: "USD",
    image: u("photo-1556228724-91ec8a83d2e0"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-lip-1",
    brand: "Tara",
    name: "Plush Lip Balm",
    category: "lip",
    tags: ["hydrating", "barrier-repair"],
    notes: "Honey and lanolin. For the windburn months.",
    price: 18,
    priceCurrency: "USD",
    image: u("photo-1599733589046-9c3e3e1b95d4"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-supp-1",
    brand: "Inner",
    name: "Magnesium Glycinate",
    category: "supplement",
    tags: ["calming"],
    notes: "Evening dose to soften the edges of a stress week.",
    price: 26,
    priceCurrency: "USD",
    image: u("photo-1584017911766-d451b3d0e843"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-supp-2",
    brand: "Inner",
    name: "Iron + Vitamin C",
    category: "supplement",
    tags: ["brightening"],
    notes: "Taken with food during your bleed week.",
    price: 24,
    priceCurrency: "USD",
    image: u("photo-1607005181894-1c8d1f3d9d04"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-body-1",
    brand: "Lumea",
    name: "Silk Body Butter",
    category: "bodycare",
    tags: ["hydrating", "barrier-repair"],
    notes: "Whipped shea. For shoulder season skin.",
    price: 32,
    priceCurrency: "USD",
    image: u("photo-1571175443880-49e1d25b2bc5"),
    source: "suggested",
    addedAt: 0,
  },
  {
    id: "sug-frag-1",
    brand: "Solene",
    name: "Iris & Tea Eau de Parfum",
    category: "fragrance",
    tags: ["calming"],
    notes: "Powdery iris over warm bergamot. A signature for low-key days.",
    price: 88,
    priceCurrency: "USD",
    image: u("photo-1541643600914-78b084683601"),
    source: "suggested",
    addedAt: 0,
  },
];

export const STARTER_VANITY: Product[] = [
  {
    id: "own-cleanse-1",
    brand: "Cetaphil",
    name: "Gentle Skin Cleanser",
    category: "cleanser",
    tags: ["hydrating", "fragrance-free", "barrier-repair"],
    notes: "The reliable one. Travel-size in your carry-on.",
    image: u("photo-1556228578-0d85b1a4d571"),
    source: "owned",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
    finishesIn: 24,
  },
  {
    id: "own-serum-1",
    brand: "The Ordinary",
    name: "Hyaluronic Acid 2% + B5",
    category: "serum",
    tags: ["hydrating", "hyaluronic"],
    image: u("photo-1620916566398-39f1143ab7be"),
    source: "owned",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
    finishesIn: 12,
  },
  {
    id: "own-serum-2",
    brand: "The Ordinary",
    name: "Niacinamide 10% + Zinc",
    category: "serum",
    tags: ["balancing", "niacinamide"],
    image: u("photo-1608248543803-ba4f8c70ae0b"),
    source: "owned",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
    finishesIn: 6,
  },
  {
    id: "own-moist-1",
    brand: "La Roche-Posay",
    name: "Toleriane Double Repair",
    category: "moisturizer",
    tags: ["hydrating", "ceramides", "barrier-repair"],
    image: u("photo-1612817159949-195b6eb9e31a"),
    source: "owned",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    finishesIn: 30,
  },
  {
    id: "own-spf-1",
    brand: "Beauty of Joseon",
    name: "Relief Sun Rice + Probiotics",
    category: "spf",
    tags: ["spf", "antioxidant", "hydrating"],
    image: u("photo-1556228841-a3c527ebefe5"),
    source: "owned",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    finishesIn: 45,
  },
  {
    id: "own-mask-1",
    brand: "Laneige",
    name: "Water Sleeping Mask",
    category: "mask",
    tags: ["hydrating", "calming"],
    image: u("photo-1620916297893-9b5a08b14a91"),
    source: "owned",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 200,
    finishesIn: 18,
  },
  {
    id: "own-eye-1",
    brand: "Kiehl's",
    name: "Avocado Eye Cream",
    category: "eye",
    tags: ["hydrating", "calming"],
    image: u("photo-1599305445671-ac291c95aaa9"),
    source: "owned",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 45,
    finishesIn: 9,
  },
  {
    id: "own-lip-1",
    brand: "Aquaphor",
    name: "Lip Repair",
    category: "lip",
    tags: ["hydrating", "barrier-repair"],
    image: u("photo-1599733589046-9c3e3e1b95d4"),
    source: "owned",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    finishesIn: 60,
  },
];
